const app = document.getElementById('app');

const state = {
  role: 'candidate',
  sector: 'All sectors',
  onboardingStep: 1,
  selectedResume: 'Primary CV',
  applied: new Set(),
  saved: new Set([3, 8]),
  selectedCategory: 'All'
};

const categories = [
  ['All','◈'],['Technology','⌘'],['Marketing','◎'],['Sales','↗'],['Finance','৳'],['HR','◉'],
  ['Design','✦'],['Operations','▦'],['Customer Support','☏'],['Healthcare','✚'],['Education','▤'],['Other','＋']
];

const jobs = [
  {id:1,title:'Junior Backend Engineer',company:'Nexa Labs',category:'Technology',loc:'Dhaka · Hybrid',type:'Full-time',salary:'৳45k–65k',score:94,skills:['Python','Django','REST API'],logo:'NL',posted:'2h ago',applicants:38,summary:'Build reliable APIs and backend services for a growing product team.',responsibilities:['Develop and maintain REST APIs','Work with PostgreSQL and production data flows','Write tests and collaborate through code review','Support deployment and monitoring workflows'],requirements:['Strong Python fundamentals','Django or similar web framework','SQL and Git','Good communication and problem solving'],preferred:['Docker','Redis','Cloud deployment']},
  {id:2,title:'Digital Marketing Executive',company:'BluePeak Consumer',category:'Marketing',loc:'Dhaka · On-site',type:'Full-time',salary:'৳35k–50k',score:92,skills:['Meta Ads','Content','Analytics'],logo:'BP',posted:'4h ago',applicants:54,summary:'Plan campaigns, manage social channels and turn marketing data into growth actions.',responsibilities:['Plan paid and organic campaigns','Coordinate content calendars','Track CAC, CTR and conversion metrics','Prepare weekly performance reports'],requirements:['Hands-on social media marketing','Basic copywriting and campaign analytics','Excel or Google Sheets','Clear communication'],preferred:['Meta Ads certification','Canva','GA4']},
  {id:3,title:'Accounts Officer',company:'Meridian Group',category:'Finance',loc:'Dhaka · On-site',type:'Full-time',salary:'৳38k–55k',score:90,skills:['Accounting','Excel','VAT/Tax'],logo:'MG',posted:'Today',applicants:71,summary:'Maintain accounts, support month-end closing and prepare accurate financial records.',responsibilities:['Record daily transactions','Prepare bank reconciliations','Support VAT and tax documentation','Assist month-end close'],requirements:['BBA/BCom in Accounting or Finance','Strong Excel skills','Knowledge of basic accounting standards','Attention to detail'],preferred:['ERP experience','QuickBooks','Corporate accounting exposure']},
  {id:4,title:'HR & People Operations Executive',company:'Lumen Services',category:'HR',loc:'Dhaka · Hybrid',type:'Full-time',salary:'৳40k–58k',score:88,skills:['Recruitment','HRIS','Employee Relations'],logo:'LS',posted:'1d ago',applicants:46,summary:'Support recruitment, onboarding, employee records and day-to-day people operations.',responsibilities:['Coordinate recruitment pipelines','Run onboarding and employee documentation','Maintain HRIS records','Support engagement activities'],requirements:['Business/HR academic background','Professional communication','Excel/Sheets','Confidential data handling'],preferred:['HRIS tools','Labour law basics','Employer branding']},
  {id:5,title:'UI/UX Designer',company:'Northstar Studio',category:'Design',loc:'Remote',type:'Full-time',salary:'৳55k–80k',score:87,skills:['Figma','UX Research','Prototyping'],logo:'NS',posted:'1d ago',applicants:93,summary:'Design accessible product experiences from research through interactive prototypes.',responsibilities:['Create user flows and wireframes','Build polished UI in Figma','Prototype key interactions','Collaborate with product and engineering'],requirements:['Strong portfolio','Figma proficiency','UX fundamentals','Responsive design understanding'],preferred:['Design systems','Usability testing','Motion design']},
  {id:6,title:'Sales Development Representative',company:'GrowthGrid',category:'Sales',loc:'Dhaka · Hybrid',type:'Full-time',salary:'৳30k–45k + incentive',score:86,skills:['B2B Sales','CRM','Lead Generation'],logo:'GG',posted:'2d ago',applicants:64,summary:'Create qualified sales opportunities through research, outreach and disciplined CRM work.',responsibilities:['Research target accounts','Run outbound email and calls','Qualify prospects','Maintain CRM hygiene'],requirements:['Strong spoken communication','Goal-oriented mindset','Basic CRM familiarity','Professional English/Bangla'],preferred:['HubSpot','SaaS sales','LinkedIn prospecting']},
  {id:7,title:'Operations Coordinator',company:'Pathao Commerce',category:'Operations',loc:'Dhaka · On-site',type:'Full-time',salary:'৳35k–48k',score:84,skills:['Operations','Excel','Vendor Coordination'],logo:'PC',posted:'2d ago',applicants:88,summary:'Coordinate daily operational workflows, vendors, reporting and issue resolution.',responsibilities:['Track daily operational KPIs','Coordinate vendors and internal teams','Resolve escalations','Prepare reports'],requirements:['Strong organization','Excel/Sheets','Problem-solving','Comfort with fast-paced work'],preferred:['Logistics experience','Dashboard tools','Process documentation']},
  {id:8,title:'Customer Support Specialist',company:'NovaCare',category:'Customer Support',loc:'Remote',type:'Full-time',salary:'৳28k–42k',score:83,skills:['Customer Support','CRM','Communication'],logo:'NC',posted:'3d ago',applicants:112,summary:'Help customers through chat, email and structured escalation while maintaining service quality.',responsibilities:['Respond to customer queries','Document cases in CRM','Escalate technical issues','Track satisfaction and response SLA'],requirements:['Excellent written communication','Empathy and patience','Basic computer literacy','Shift flexibility'],preferred:['Zendesk','SaaS support','English fluency']},
  {id:9,title:'Registered Nurse — General Ward',company:'GreenLife Hospital',category:'Healthcare',loc:'Dhaka · On-site',type:'Full-time',salary:'৳32k–50k',score:81,skills:['Patient Care','Nursing','Clinical Documentation'],logo:'GH',posted:'3d ago',applicants:39,summary:'Provide safe patient care, maintain clinical documentation and coordinate with medical teams.',responsibilities:['Provide bedside nursing care','Record vitals and medication administration','Maintain patient documentation','Coordinate with doctors and attendants'],requirements:['Diploma/BSc in Nursing','Valid professional registration','Clinical communication','Patient safety knowledge'],preferred:['Ward experience','BLS certification','Hospital HIS familiarity']},
  {id:10,title:'English Teacher — Secondary',company:'BrightPath School',category:'Education',loc:'Narayanganj · On-site',type:'Full-time',salary:'৳30k–45k',score:80,skills:['Teaching','Lesson Planning','Assessment'],logo:'BS',posted:'4d ago',applicants:58,summary:'Teach secondary-level English using structured lessons, assessment and student feedback.',responsibilities:['Plan and deliver lessons','Prepare assessments','Provide student feedback','Coordinate with academic team'],requirements:['Relevant degree','Strong English communication','Classroom management','Lesson planning'],preferred:['B.Ed','EdTech tools','Cambridge curriculum exposure']},
  {id:11,title:'Machine Learning Intern',company:'Axiom AI',category:'Technology',loc:'Remote',type:'Internship',salary:'৳25k–35k',score:79,skills:['Python','Scikit-learn','Pandas'],logo:'AI',posted:'5d ago',applicants:120,summary:'Support practical ML experiments, data preparation and model evaluation.',responsibilities:['Prepare datasets','Train baseline models','Evaluate experiments','Document findings'],requirements:['Python','ML fundamentals','Pandas/Numpy','Learning mindset'],preferred:['PyTorch','Kaggle','MLOps basics']},
  {id:12,title:'Procurement Executive',company:'Atlas Manufacturing',category:'Operations',loc:'Gazipur · On-site',type:'Full-time',salary:'৳42k–60k',score:77,skills:['Procurement','Vendor Management','ERP'],logo:'AM',posted:'6d ago',applicants:44,summary:'Manage sourcing, purchase documentation, vendor follow-up and procurement reporting.',responsibilities:['Source suppliers','Prepare comparative statements','Track purchase orders','Maintain vendor records'],requirements:['Business degree','Negotiation','Excel','Documentation discipline'],preferred:['ERP','Manufacturing procurement','Import documentation']}
];

const candidates = [
  {id:1,name:'Ayesha Karim',role:'Marketing Executive',sector:'Marketing',score:92,exp:'3 yrs',skills:['Meta Ads','Content','GA4'],stage:'Shortlisted'},
  {id:2,name:'Rafi Hasan',role:'Backend Developer',sector:'Technology',score:89,exp:'2 yrs',skills:['Python','Django','SQL'],stage:'Screening'},
  {id:3,name:'Nusrat Jahan',role:'Accounts Officer',sector:'Finance',score:88,exp:'2 yrs',skills:['Accounting','Excel','VAT'],stage:'Interview'},
  {id:4,name:'Shafin Ahmed',role:'Sales Executive',sector:'Sales',score:86,exp:'3 yrs',skills:['B2B Sales','CRM','Prospecting'],stage:'Applied'},
  {id:5,name:'Maliha Noor',role:'UI/UX Designer',sector:'Design',score:84,exp:'2 yrs',skills:['Figma','Research','Prototype'],stage:'Interview'}
];

function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function go(r){location.hash=r}
function route(){return location.hash.replace('#','')||'/'}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function brand(){return `<a class="brand" href="#/"><span class="brand-mark">C</span><span>CareerMate</span></a>`}
function initials(name){return name.split(' ').map(x=>x[0]).join('').slice(0,2)}

function landing(){
  return `<nav class="public-nav"><div class="container nav-inner">${brand()}<div class="nav-links"><a href="#sectors">Job sectors</a><a href="#features">Candidate tools</a><a href="#ai">AI</a><a href="#employers">Employers</a></div><div class="nav-actions"><button class="btn btn-ghost" onclick="go('/login')">Sign in</button><button class="btn btn-primary" onclick="go('/signup')">Create account</button></div></div></nav>
  <section class="hero"><div class="container hero-wrap"><div><span class="badge mint"><span class="dot"></span> AI-powered job & hiring platform</span><h1>One career platform for <span>every profession.</span></h1><p>Discover jobs, apply with the right CV, build a professional profile, track applications and use AI for role matching, resume improvement and interview preparation — across technology, business, creative, service, healthcare and education careers.</p><div class="hero-actions"><button class="btn btn-primary" onclick="go('/signup')">Find jobs →</button><button class="btn btn-dark" onclick="state.role='employer';go('/employer')">Hire talent</button></div><div class="hero-trust"><span>✓ Multi-sector job discovery</span><span>✓ CV & profile intelligence</span><span>✓ Candidate + employer workspaces</span></div></div>
  <div class="hero-ui"><div class="floating-chip chip-a">✦ 18 personalized matches</div><div class="floating-chip chip-b">✓ Application ready</div><div class="hero-window"><div class="window-top"><b>Recommended for you</b><span class="badge mint">AI ranked</span></div><div class="window-body"><div class="mock-side"><div class="active"></div><div></div><div></div><div></div><div></div></div><div class="mock-main"><div class="ai-match-card"><small>TOP MATCH TODAY</small><div class="match-score">92%</div><b>Digital Marketing Executive</b><p style="font-size:12px;color:#cbd6ed;margin:6px 0 0">Skills, location and experience align strongly.</p></div>${jobs.slice(1,4).map(j=>miniJob(j)).join('')}</div></div></div></div></div></section>
  <div class="container stats-bar"><div class="card stat"><strong>12+</strong><span>career sectors in one demo</span></div><div class="card stat"><strong>AI</strong><span>match, CV, prep & hiring assist</span></div><div class="card stat"><strong>3</strong><span>candidate, employer & admin workspaces</span></div><div class="card stat"><strong>1</strong><span>complete application journey</span></div></div>
  <section class="section" id="sectors"><div class="container"><span class="kicker">Not engineering-only</span><h2 class="section-title">Search by profession, sector and work style.</h2><p class="section-copy">The same platform can serve technical and non-technical candidates without forcing every profile into a software-skills template.</p><div class="sector-grid">${categories.filter(x=>x[0]!=='All').map(c=>`<button class="sector-card card" onclick="state.selectedCategory='${c[0]}';go('/jobs')"><span>${c[1]}</span><b>${c[0]}</b><small>${jobs.filter(j=>j.category===c[0]).length || 'More'} live demo roles</small></button>`).join('')}</div></div></section>
  <section class="section" id="features"><div class="container"><span class="kicker">Candidate workspace</span><h2 class="section-title">From account creation to application outcome.</h2><div class="features-grid">${[['⌕','Job discovery','Search and filter by sector, location, salary, experience, work mode and job type.'],['▤','CV manager','Upload multiple CVs, parse information, choose a primary CV and tailor for a target role.'],['◉','Professional profile','Experience, education, skills, certifications, portfolio, preferences and visibility controls.'],['✓','Guided application','Choose CV, answer screening questions, review application and submit.'],['◫','Application tracker','Track applied, screening, interview, assessment, offer and rejected stages.'],['✦','AI career help','Match explanation, CV suggestions, cover-letter draft, interview prep and skill-gap plan.']].map(x=>`<div class="card feature"><div class="feature-icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></div></section>
  <section class="section ai-section" id="ai"><div class="container ai-grid"><div><span class="kicker" style="color:var(--mint)">AI with defined responsibilities</span><h2 class="section-title">AI helps the user decide and prepare. It does not invent qualifications.</h2><p class="section-copy" style="color:#aebbd9">Candidate AI is contextual to the selected profession and job. Employer AI helps write structured jobs and summarize evidence, while hiring decisions remain with people.</p><button class="btn btn-mint" onclick="go('/ai-coach')">Open AI career assistant</button></div><div class="ai-list">${[['Job match explainer','Shows evidence-backed strengths, gaps and preference alignment.'],['CV tailoring','Suggests truthful improvements for a selected role.'],['Application copilot','Drafts screening answers and cover letters from user-provided facts.'],['Interview practice','Generates sector-specific practice questions and feedback.'],['Employer assistant','Improves job descriptions and summarizes candidate evidence.']].map((x,i)=>`<div class="ai-item"><div class="feature-icon" style="background:rgba(62,214,178,.14);color:var(--mint);margin:0">${i+1}</div><div><b>${x[0]}</b><span>${x[1]}</span></div></div>`).join('')}</div></div></section>
  <section class="section" id="employers"><div class="container"><span class="kicker">Employer workspace</span><h2 class="section-title">Post any type of role and manage the complete hiring pipeline.</h2><p class="section-copy">Choose a job sector, define role-specific requirements, review candidates, shortlist, interview, message, analyze funnel performance and maintain a verified company profile.</p><div style="margin-top:22px;display:flex;gap:10px;flex-wrap:wrap"><button class="btn btn-dark" onclick="state.role='employer';go('/employer')">Open employer workspace</button><button class="btn btn-ghost" onclick="go('/admin')">Open admin workspace</button></div></div></section>
  <footer class="footer"><div class="container"><div class="footer-grid"><div>${brand()}<p style="font-size:13px;line-height:1.7;max-width:330px">Production-oriented frontend concept for a multi-sector AI recruitment platform.</p></div><div><h4>Candidates</h4><a>Jobs</a><a>CVs</a><a>Applications</a><a>AI Coach</a></div><div><h4>Employers</h4><a>Post jobs</a><a>Candidates</a><a>Pipeline</a><a>Analytics</a></div><div><h4>Platform</h4><a>Admin</a><a>Privacy</a><a>Safety</a><a>Support</a></div></div><div class="footer-bottom">© 2026 CareerMate · Interactive HTML/CSS/JS product demo.</div></div></footer>`;
}

function miniJob(j){return `<div class="job-row"><div style="display:flex;gap:10px;align-items:center"><div class="job-logo">${j.logo}</div><div><b style="font-size:12px">${j.title}</b><div style="font-size:10px;color:#778199">${j.category} · ${j.company}</div></div></div><span class="badge mint">${j.score}%</span></div>`}

function auth(type='login'){
  const signup=type==='signup';
  return `<div class="auth-shell"><div class="auth-visual"><div>${brand()}</div><div class="auth-feature"><span class="badge mint">Career + hiring workspace</span><h2>${signup?'Create one profile. Explore every relevant sector.':'Continue your job search or hiring workflow.'}</h2><p>Job discovery, CVs, applications, messages, AI guidance and employer hiring tools all live in one platform.</p></div><div class="mini-proof"><span>Multi-sector jobs</span><span>CV intelligence</span><span>Application tracking</span></div></div><div class="auth-panel"><div class="auth-card"><span class="badge dark">${signup?'Create account':'Secure sign in'}</span><h1>${signup?'Join CareerMate':'Welcome back'}</h1><p>${signup?'Choose how you want to use the platform.':'Use your email and password to continue.'}</p>${signup?`<div class="choice-grid auth-role-grid"><button class="choice selected" onclick="pickRole(this,'candidate')"><div class="choice-icon">◉</div><b>Job seeker</b><small>Find jobs & apply</small></button><button class="choice" onclick="pickRole(this,'employer')"><div class="choice-icon">▦</div><b>Employer</b><small>Post jobs & hire</small></button></div>`:''}<form class="form" onsubmit="event.preventDefault();${signup?"signupNext()":"go('/dashboard')"}">${signup?`<div class="field"><label>Full name / company contact</label><input class="input" required placeholder="Enter name"></div>`:''}<div class="field"><label>Email address</label><input class="input" type="email" required placeholder="name@example.com"></div><div class="field"><label>Password</label><input class="input" type="password" required placeholder="••••••••"></div><button class="btn btn-primary" style="width:100%">${signup?'Create account':'Sign in'}</button></form><div class="auth-divider">or</div><button class="btn btn-ghost social-btn">G&nbsp;&nbsp; Continue with Google</button><p style="text-align:center;font-size:13px">${signup?'Already have an account?':'New here?'} <a style="color:var(--blue);font-weight:800" href="#/${signup?'login':'signup'}">${signup?'Sign in':'Create account'}</a></p></div></div></div>`
}
function pickRole(el,role){state.role=role;document.querySelectorAll('.auth-role-grid .choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected')}
function signupNext(){state.role==='employer'?go('/company-setup'):go('/onboarding')}

function onboarding(){
  const s=state.onboardingStep;
  const content=[
    `<h1>What type of work are you looking for?</h1><p class="section-copy">Choose your main sector. You can change it later or follow multiple sectors.</p><div class="sector-select-grid">${categories.filter(x=>x[0]!=='All').map(c=>`<button class="sector-card choice ${state.sector===c[0]?'selected':''}" onclick="state.sector='${c[0]}';render()"><span>${c[1]}</span><b>${c[0]}</b></button>`).join('')}</div>`,
    `<h1>Set your job preferences</h1><p class="section-copy">These signals improve ranking but never hide all other jobs.</p><div class="grid-12"><div class="col-6 field"><label>Target role</label><input class="input" placeholder="e.g. Accounts Officer, Teacher, Designer"></div><div class="col-6 field"><label>Experience level</label><select class="input"><option>Entry level / Fresher</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select></div><div class="col-6 field"><label>Preferred location</label><input class="input" value="Dhaka / Remote"></div><div class="col-6 field"><label>Job type</label><select class="input"><option>Full-time</option><option>Part-time</option><option>Internship</option><option>Contract</option></select></div><div class="col-6 field"><label>Minimum salary</label><input class="input" placeholder="৳ 35,000 / month"></div><div class="col-6 field"><label>Work mode</label><select class="input"><option>Any</option><option>On-site</option><option>Hybrid</option><option>Remote</option></select></div></div>`,
    `<h1>Upload your CV</h1><p class="section-copy">We’ll parse education, experience and skills so you don’t have to type everything twice.</p><div class="upload-box" onclick="toast('Demo CV selected')"><div style="font-size:38px">⇧</div><strong>Drop PDF/DOCX here or click to browse</strong><span style="color:var(--muted);font-size:12px">Max 10 MB · PDF or DOCX</span></div><div class="suggestion"><b>AI rule:</b> CareerMate may suggest missing information but should not create fake experience, degrees or certifications.</div>`,
    `<h1>Review your professional profile</h1><p class="section-copy">You can refine these sections later.</p><div class="profile-check-list">${[['Basic information','Name, headline, location'],['Experience','Work history and responsibilities'],['Education','Degrees, institute and dates'],['Skills','Role-specific hard and soft skills'],['Certifications','Optional verified credentials'],['Portfolio & links','Website, LinkedIn or work samples']].map((x,i)=>`<div class="profile-check"><span class="check-icon">✓</span><div><b>${x[0]}</b><small>${x[1]}</small></div><button class="btn btn-ghost">Edit</button></div>`).join('')}</div>`,
    `<h1>Your workspace is ready</h1><p class="section-copy">CareerMate will start with <b>${state.sector}</b> roles, but you can search any sector.</p><div class="ready-visual"><div class="ready-ring">92%</div><div><b>Profile ready for matching</b><p>Job preferences, CV and profile can now power recommendations.</p></div></div>`
  ][s-1];
  return `<div class="onboarding-shell"><div class="onboarding-card"><div style="display:flex;justify-content:center">${brand()}</div><div class="stepper">${[1,2,3,4,5].map((n,i)=>`${i?'<span class="step-line"></span>':''}<div class="step ${n<s?'done':n===s?'active':''}"><div class="circle">${n<s?'✓':n}</div></div>`).join('')}</div><div class="card onboard-panel">${content}<div class="onboard-actions"><button class="btn btn-ghost" ${s===1?'disabled':''} onclick="state.onboardingStep=Math.max(1,state.onboardingStep-1);render()">Back</button><button class="btn btn-primary" onclick="${s===5?"go('/dashboard')":"state.onboardingStep++;render()"}">${s===5?'Open dashboard':'Continue'}</button></div></div></div></div>`
}

function sidebar(employer=false,admin=false){
  const candidateNav=[['/dashboard','⌂','Home'],['/jobs','⌕','Find jobs'],['/saved','♡','Saved jobs'],['/resume','▤','CV & Resume'],['/tracker','◫','Applications'],['/ai-coach','✦','AI Career Coach'],['/messages','✉','Messages'],['/notifications','◌','Notifications'],['/profile','◉','Profile'],['/settings','⚙','Settings']];
  const employerNav=[['/employer','⌂','Overview'],['/post-job','＋','Post a job'],['/manage-jobs','▤','Manage jobs'],['/candidates','◎','Candidates'],['/pipeline','◫','Hiring pipeline'],['/employer-messages','✉','Messages'],['/analytics','↗','Analytics'],['/company-profile','▦','Company profile'],['/settings','⚙','Settings']];
  const adminNav=[['/admin','⌂','Overview'],['/admin-users','◉','Users'],['/admin-jobs','▤','Job moderation'],['/admin-reports','!','Reports & safety'],['/settings','⚙','Settings']];
  const nav=admin?adminNav:(employer?employerNav:candidateNav);
  return `<aside class="sidebar ${employer?'employer-accent':''}"><div class="side-brand">${brand()}</div><div class="side-label">${admin?'PLATFORM ADMIN':employer?'EMPLOYER WORKSPACE':'CANDIDATE WORKSPACE'}</div><nav class="side-nav">${nav.map(n=>`<a class="${route()===n[0]?'active':''}" href="#${n[0]}"><span>${n[1]}</span>${n[2]}</a>`).join('')}</nav>${!admin?`<div class="side-switch"><small>Switch workspace</small><button onclick="${employer?"state.role='candidate';go('/dashboard')":"state.role='employer';go('/employer')"}">${employer?'◉ Candidate view':'▦ Employer demo'}</button></div>`:''}<div class="side-user"><div class="candidate-avatar">${admin?'AD':employer?'NL':'TR'}</div><div><b>${admin?'Platform Admin':employer?'Nexa Labs':'Tanvir Rahman'}</b><small>${admin?'Operations':employer?'Verified employer':state.sector}</small></div></div></aside>`
}
function shell(content,employer=false,admin=false){return `<div class="app-shell">${sidebar(employer,admin)}<main class="app-main"><header class="topbar"><button class="mobile-menu btn btn-ghost" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><div class="global-search"><span>⌕</span><input placeholder="Search jobs, companies, people..." onkeydown="if(event.key==='Enter')go('/jobs')"></div><div class="top-actions"><button class="icon-btn" onclick="go('/notifications')">◌<span class="notif-dot"></span></button><button class="btn btn-primary hide-mobile" onclick="${employer?"go('/post-job')":"go('/jobs')"}">${employer?'+ Post job':'Find jobs'}</button></div></header><div class="content">${content}</div></main></div>`}

function dashboard(){
  const recommended=jobs.slice(0,4);
  return shell(`<div class="page-head"><div><h1>Good afternoon, Tanvir</h1><p>Your profile is active across <b>${state.sector}</b> and other relevant sectors.</p></div><button class="btn btn-primary" onclick="go('/jobs')">Explore jobs</button></div>
  <div class="grid-12"><div class="col-8"><div class="ai-banner"><span class="badge mint">✦ AI Career Insight</span><h2>Your strongest opportunities are broader than one job title.</h2><p>Based on your selected sector, profile evidence and preferences, CareerMate can recommend adjacent roles instead of matching only exact keywords.</p><div class="hero-actions" style="margin-top:18px"><button class="btn btn-mint" onclick="go('/ai-coach')">Ask AI what fits me</button><button class="btn btn-ghost light-ghost" onclick="go('/profile')">Improve profile</button></div></div></div><div class="col-4 card metric"><small>Profile strength</small><strong>82%</strong><div class="progress"><span style="width:82%"></span></div><div class="trend" style="margin-top:8px">3 sections can improve</div></div></div>
  <div class="quick-actions"><button class="quick card" onclick="go('/jobs')"><span>⌕</span><b>Find jobs</b><small>Search all sectors</small></button><button class="quick card" onclick="go('/resume')"><span>▤</span><b>Upload CV</b><small>Manage versions</small></button><button class="quick card" onclick="go('/tracker')"><span>◫</span><b>Applications</b><small>Track progress</small></button><button class="quick card" onclick="go('/ai-coach')"><span>✦</span><b>Ask AI</b><small>Career help</small></button></div>
  <div class="section-row"><div><h2>Recommended jobs</h2><p>Across sectors, ranked by your profile.</p></div><button class="btn btn-ghost" onclick="go('/jobs')">View all</button></div><div class="job-list">${recommended.map(jobCard).join('')}</div>
  <div class="grid-12" style="margin-top:18px"><div class="col-7 card panel"><div class="section-row"><div><h3>Application activity</h3><p>Your recent progress</p></div><button class="btn btn-ghost" onclick="go('/tracker')">Open tracker</button></div>${applicationRows(true)}</div><div class="col-5 card panel"><h3>Complete your profile</h3><div class="check-progress">${[['Add portfolio/work sample',false],['Verify education',true],['Add salary preference',true],['Add 3 more skills',false]].map(x=>`<div><span class="${x[1]?'done':''}">${x[1]?'✓':'○'}</span>${x[0]}</div>`).join('')}</div></div></div>`) 
}

function jobCard(j){return `<div class="card job-card" data-cat="${j.category}" onclick="go('/job/${j.id}')"><div class="job-logo">${j.logo}</div><div><div class="job-title-line"><span class="badge dark">${j.category}</span><span class="job-age">${j.posted}</span></div><h3>${j.title}</h3><div class="job-meta"><span>${j.company}</span><span>${j.loc}</span><span>${j.type}</span><span>${j.salary}</span></div><div class="skills">${j.skills.map(s=>`<span class="skill">${s}</span>`).join('')}</div></div><div class="job-side"><button class="save-btn ${state.saved.has(j.id)?'saved':''}" onclick="event.stopPropagation();toggleSave(${j.id},this)">${state.saved.has(j.id)?'♥':'♡'}</button><div class="score-ring" style="--score:${j.score}"><b>${j.score}%</b></div><small>AI match</small></div></div>`}
function toggleSave(id,el){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);el.classList.toggle('saved');el.textContent=state.saved.has(id)?'♥':'♡';toast(state.saved.has(id)?'Job saved':'Removed from saved')}
function filterJobs(cat,el){state.selectedCategory=cat;document.querySelectorAll('.category-pill').forEach(x=>x.classList.remove('active'));if(el)el.classList.add('active');document.querySelectorAll('.job-card').forEach(card=>card.style.display=(cat==='All'||card.dataset.cat===cat)?'grid':'none')}

function jobsPage(){
  const filtered=state.selectedCategory==='All'?jobs:jobs.filter(j=>j.category===state.selectedCategory);
  return shell(`<div class="page-head"><div><h1>Find jobs</h1><p>Search across technical and non-technical professions.</p></div><button class="btn btn-soft" onclick="toast('Job alert created')">Create job alert</button></div>
  <div class="job-search-hero card"><div class="search-field"><span>⌕</span><input placeholder="Job title, skill or company"></div><div class="search-field"><span>⌖</span><input placeholder="Dhaka, Bangladesh or Remote"></div><button class="btn btn-primary" onclick="toast('Search updated')">Search jobs</button></div>
  <div class="category-scroll">${categories.map(c=>`<button class="category-pill ${state.selectedCategory===c[0]?'active':''}" onclick="filterJobs('${c[0]}',this)"><span>${c[1]}</span>${c[0]}</button>`).join('')}</div>
  <div class="filter-toolbar"><button class="filter active">Most relevant</button><button class="filter">Experience ⌄</button><button class="filter">Salary ⌄</button><button class="filter">Job type ⌄</button><button class="filter">Work mode ⌄</button><button class="filter">Date posted ⌄</button><button class="filter">Company ⌄</button></div>
  <div class="grid-12"><div class="col-8"><div class="result-count"><b>${filtered.length} demo opportunities</b><span>Personalized ranking on</span></div><div class="job-list">${filtered.map(jobCard).join('')}</div></div><div class="col-4"><div class="card panel sticky-panel"><span class="badge mint">✦ AI Search</span><h3>Describe what you actually want</h3><p class="muted-copy">Natural-language preferences can refine results beyond rigid filters.</p><textarea class="input" style="min-height:115px" placeholder="Example: Entry-level finance role near Dhaka, regular office hours, salary above ৳35k, strong learning environment..."></textarea><button class="btn btn-primary" style="width:100%;margin-top:10px" onclick="toast('AI preferences applied')">Refine results</button><div class="suggestion"><b>AI won’t hide alternatives:</b> it re-ranks results and explains why.</div></div></div></div>`)
}

function jobDetail(id){
  const j=jobs.find(x=>x.id==id)||jobs[0];
  return shell(`<div class="back-row"><button class="btn btn-ghost" onclick="history.back()">← Back to jobs</button></div><div class="grid-12"><div class="col-8"><div class="card detail-hero"><div class="detail-title"><div class="job-logo big">${j.logo}</div><div><div class="job-title-line"><span class="badge dark">${j.category}</span><span class="badge mint">${j.score}% AI match</span></div><h1>${j.title}</h1><div class="job-meta"><span>${j.company}</span><span>${j.loc}</span><span>${j.type}</span><span>${j.salary}</span></div><div class="job-meta"><span>${j.posted}</span><span>${j.applicants} applicants</span></div></div></div><div class="detail-actions"><button class="btn btn-primary" onclick="go('/apply/${j.id}')">Apply now</button><button class="btn btn-soft" onclick="toggleSave(${j.id},this)">${state.saved.has(j.id)?'♥ Saved':'♡ Save job'}</button><button class="btn btn-ghost" onclick="go('/ai-coach')">✦ Ask AI about this job</button></div></div>
  <div class="card detail-section"><h3>About the role</h3><p>${j.summary}</p><h3>What you’ll do</h3><ul>${j.responsibilities.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Requirements</h3><ul>${j.requirements.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Preferred</h3><div class="skills">${j.preferred.map(x=>`<span class="skill">${x}</span>`).join('')}</div></div>
  <div class="card detail-section"><h3>About ${j.company}</h3><p>Verified employer · ${j.category} · Bangladesh. Company information, workplace details, benefits and verification signals would be managed from the employer profile in production.</p><button class="btn btn-ghost">View company profile</button></div></div>
  <div class="col-4"><div class="card panel sticky-panel"><h3>Your match breakdown</h3>${matchBreakdown(j)}<div class="suggestion"><b>AI explanation:</b> Your profile aligns strongly on role-level skills and preferred location. One or two preferred requirements are not confirmed.</div><button class="btn btn-soft" style="width:100%" onclick="go('/ai-coach')">Improve my fit</button></div><div class="card panel" style="margin-top:16px"><h3>Job safety</h3><div class="info-list"><div class="info-item"><span>Employer verification</span><b>✓ Verified</b></div><div class="info-item"><span>Application method</span><b>CareerMate</b></div><div class="info-item"><span>Fee required</span><b>No</b></div></div><button class="btn btn-ghost" style="width:100%">Report job</button></div></div></div>`)
}
function matchBreakdown(j){const vals=j.category==='Technology'?[['Role skills',94],['Experience',83],['Location',100],['Salary',91],['Work mode',100]]:[['Relevant skills',91],['Experience',86],['Education',82],['Location',100],['Preferences',94]];return `<div class="match-breakdown">${vals.map(x=>`<div class="match-row"><span>${x[0]}</span><div class="progress"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</div>`}

function applyPage(id){
  const j=jobs.find(x=>x.id==id)||jobs[0];
  return shell(`<div class="page-head"><div><span class="kicker">Application</span><h1>Apply to ${j.title}</h1><p>${j.company} · ${j.loc}</p></div><span class="badge mint">Estimated 4 minutes</span></div><div class="apply-layout"><div><div class="apply-step card"><div class="apply-step-head"><span>1</span><div><b>Choose CV / Resume</b><small>Select the version you want the employer to receive.</small></div><em>Required</em></div><div class="resume-choice selected" onclick="selectResume(this,'Primary CV')"><div class="file-icon">PDF</div><div><b>Primary CV</b><small>Tanvir_Rahman_CV.pdf · Updated today</small></div><span>✓</span></div><div class="resume-choice" onclick="selectResume(this,'Marketing CV')"><div class="file-icon">PDF</div><div><b>${j.category} CV</b><small>Role-tailored version · Updated 3 days ago</small></div><span></span></div><button class="btn btn-ghost" onclick="go('/resume')">+ Upload another CV</button></div>
  <div class="apply-step card"><div class="apply-step-head"><span>2</span><div><b>Screening questions</b><small>Answers should be truthful and may be reviewed by the employer.</small></div><em>Required</em></div><div class="field"><label>How many years of relevant experience do you have?</label><select class="input"><option>Less than 1 year</option><option>1–2 years</option><option>2–4 years</option><option>4+ years</option></select></div><div class="field"><label>Why are you interested in this role?</label><textarea class="input" style="min-height:110px" placeholder="Write your answer..."></textarea><button class="btn btn-soft" onclick="toast('AI draft generated from your profile facts')">✦ Draft with AI</button></div><div class="field"><label>Expected monthly salary</label><input class="input" placeholder="৳ 50,000"></div></div>
  <div class="apply-step card"><div class="apply-step-head"><span>3</span><div><b>Supporting information</b><small>Optional links or a short note.</small></div><em>Optional</em></div><div class="field"><label>Portfolio / LinkedIn / Work sample</label><input class="input" placeholder="https://..."></div><div class="field"><label>Cover note</label><textarea class="input" style="min-height:100px" placeholder="Optional short note to the employer"></textarea></div></div></div>
  <aside><div class="card panel sticky-panel"><h3>Review before submitting</h3><div class="info-list"><div class="info-item"><span>Role</span><b>${j.title}</b></div><div class="info-item"><span>Company</span><b>${j.company}</b></div><div class="info-item"><span>CV</span><b id="selectedResumeLabel">${state.selectedResume}</b></div><div class="info-item"><span>Profile</span><b>Attached</b></div></div><div class="consent-box"><input type="checkbox" checked> <span>I confirm the information I submit is accurate and may be shared with this employer for this application.</span></div><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="submitApplication(${j.id})">Submit application</button><button class="btn btn-ghost" style="width:100%;margin-top:8px" onclick="toast('Saved as draft')">Save draft</button></div></aside></div>`)
}
function selectResume(el,name){document.querySelectorAll('.resume-choice').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');state.selectedResume=name;const lab=document.getElementById('selectedResumeLabel');if(lab)lab.textContent=name}
function submitApplication(id){state.applied.add(id);go('/application-success/'+id)}
function applicationSuccess(id){const j=jobs.find(x=>x.id==id)||jobs[0];return shell(`<div class="success-wrap"><div class="success-icon">✓</div><span class="badge mint">Application submitted</span><h1>Your application is on its way.</h1><p>${j.company} received your application for <b>${j.title}</b>. CareerMate added it to your application tracker.</p><div class="success-actions"><button class="btn btn-primary" onclick="go('/tracker')">Track application</button><button class="btn btn-ghost" onclick="go('/jobs')">Find more jobs</button></div><div class="card success-next"><h3>AI can help with the next step</h3><div class="quick-actions"><button class="quick" onclick="go('/ai-coach')"><span>✦</span><b>Interview prep</b><small>Practice role-specific questions</small></button><button class="quick" onclick="go('/profile')"><span>◉</span><b>Strengthen profile</b><small>Improve employer visibility</small></button></div></div></div>`)}

function resumePage(){return shell(`<div class="page-head"><div><h1>CV & Resume center</h1><p>Upload multiple versions, parse profile information and tailor a CV to a selected job.</p></div><button class="btn btn-primary" onclick="document.getElementById('cvFile').click()">+ Upload CV</button><input id="cvFile" type="file" hidden accept=".pdf,.doc,.docx" onchange="toast('CV uploaded successfully')"></div><div class="grid-12"><div class="col-8"><div class="card upload-zone" onclick="document.getElementById('cvFile').click()"><span>⇧</span><b>Upload a new CV</b><p>PDF or DOCX · maximum 10 MB</p></div><div class="section-row"><div><h2>Your CVs</h2><p>Keep different truthful versions for different job families.</p></div></div>${[['Primary CV','Tanvir_Rahman_CV.pdf','General profile','82','Primary'],['Marketing CV','Tanvir_Marketing_CV.pdf','Marketing & growth','88',''],['Operations CV','Tanvir_Operations_CV.pdf','Operations & coordination','85','']].map(x=>`<div class="card cv-card"><div class="file-icon">PDF</div><div><div style="display:flex;gap:8px;align-items:center"><b>${x[0]}</b>${x[4]?'<span class="badge mint">Primary</span>':''}</div><small>${x[1]} · ${x[2]} · Updated recently</small></div><div class="cv-score"><b>${x[3]}</b><small>AI score</small></div><div class="cv-actions"><button class="btn btn-soft" onclick="toast('AI review opened')">AI review</button><button class="btn btn-ghost">⋯</button></div></div>`).join('')}</div><div class="col-4"><div class="card panel sticky-panel"><span class="badge mint">✦ CV AI</span><h3>Primary CV review</h3><div class="resume-score"><strong>82</strong></div><div class="info-list"><div class="info-item"><span>Clarity</span><b>90</b></div><div class="info-item"><span>Evidence</span><b>74</b></div><div class="info-item"><span>ATS readability</span><b>88</b></div><div class="info-item"><span>Profile completeness</span><b>78</b></div></div><div class="suggestion"><b>Sector-aware:</b> AI feedback changes based on whether the CV targets finance, education, sales, design or another field.</div><button class="btn btn-primary" style="width:100%" onclick="toast('Improvement plan generated')">Generate improvement plan</button></div></div></div>`)}

function applicationRows(compact=false){const rows=[['Digital Marketing Executive','BluePeak Consumer','Interview','Tomorrow · 3:00 PM'],['Accounts Officer','Meridian Group','Screening','Updated today'],['UI/UX Designer','Northstar Studio','Applied','2 days ago'],['Operations Coordinator','Pathao Commerce','Rejected','5 days ago']];return `<div class="tracker">${rows.slice(0,compact?3:rows.length).map(x=>`<div class="track-row ${compact?'compact':''}"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="status ${x[2].toLowerCase()}">${x[2]}</span><span>${x[3]}</span>${compact?'':`<button class="btn btn-ghost">View</button>`}</div>`).join('')}</div>`}
function tracker(){return shell(`<div class="page-head"><div><h1>Applications</h1><p>Track every job from draft through final outcome.</p></div><button class="btn btn-primary" onclick="go('/jobs')">Find more jobs</button></div><div class="application-stats"><div class="card metric"><small>Total applications</small><strong>12</strong></div><div class="card metric"><small>In progress</small><strong>6</strong></div><div class="card metric"><small>Interviews</small><strong>2</strong></div><div class="card metric"><small>Offers</small><strong>1</strong></div></div><div class="filter-toolbar"><button class="filter active">All</button><button class="filter">Drafts</button><button class="filter">Applied</button><button class="filter">Screening</button><button class="filter">Interview</button><button class="filter">Offer</button><button class="filter">Closed</button></div><div class="card panel">${applicationRows(false)}</div>`)}
function savedJobs(){const list=jobs.filter(j=>state.saved.has(j.id));return shell(`<div class="page-head"><div><h1>Saved jobs</h1><p>Roles you want to revisit before applying.</p></div><button class="btn btn-primary" onclick="go('/jobs')">Discover jobs</button></div><div class="job-list">${list.length?list.map(jobCard).join(''):'<div class="empty-state card"><span>♡</span><h3>No saved jobs</h3><p>Save roles from job search to compare them here.</p></div>'}</div>`)}

function aiCoach(){return shell(`<div class="page-head"><div><h1>AI Career Coach</h1><p>Sector-aware guidance grounded in your profile and selected jobs.</p></div><span class="badge mint">Uses profile context</span></div><div class="ai-coach-layout"><div class="card coach-chat"><div class="coach-welcome"><span class="badge">✦ CareerMate AI</span><h2>What do you need help with?</h2><div class="prompt-chips"><button class="prompt-chip" onclick="prefill('Which jobs fit my background best?')">Which jobs fit me?</button><button class="prompt-chip" onclick="prefill('Improve my CV for a finance role')">Tailor my CV</button><button class="prompt-chip" onclick="prefill('Practice interview questions for a marketing role')">Interview practice</button><button class="prompt-chip" onclick="prefill('What skills should I learn next?')">Skill-gap plan</button><button class="prompt-chip" onclick="prefill('Draft a truthful cover letter from my profile')">Cover letter</button></div></div><div class="coach-log" id="coachLog"><div class="ai-bubble"><b>CareerMate AI</b><br>I can compare your profile with a specific job, explain gaps, help improve truthful application materials, and prepare you for interviews. I won’t invent experience, degrees, certifications or achievements.</div></div><div class="coach-input"><textarea id="coachInput" placeholder="Ask about jobs, CV, application or interview preparation..."></textarea><button class="btn btn-primary" onclick="askCoach()">Send</button></div></div><div class="card panel"><h3>AI context</h3><div class="info-list"><div class="info-item"><span>Professional profile</span><div class="switch on"></div></div><div class="info-item"><span>CVs</span><div class="switch on"></div></div><div class="info-item"><span>Saved jobs</span><div class="switch on"></div></div><div class="info-item"><span>Application history</span><div class="switch"></div></div></div><h3 style="margin-top:22px">AI modes</h3><div class="mode-list"><button>Job Match Explainer</button><button>CV Review</button><button>Interview Coach</button><button>Career Roadmap</button><button>Application Writer</button></div></div></div>`)}
function prefill(t){const i=document.getElementById('coachInput');if(i){i.value=t;i.focus()}}
function askCoach(){const input=document.getElementById('coachInput');if(!input||!input.value.trim())return;const log=document.getElementById('coachLog');log.innerHTML+=`<div class="bubble me">${esc(input.value)}</div><div class="ai-bubble"><b>CareerMate AI</b><br>For this prototype, I would first identify the target sector and role, compare verified profile evidence with the job requirements, then return a prioritized answer. In production, this message would come from the AI service with clear provenance and user controls.</div>`;input.value='';log.scrollTop=log.scrollHeight}

function messages(){return shell(chatUI(false))}
function employerMessages(){return shell(chatUI(true),true)}
function chatUI(employer){return `<div class="page-head"><div><h1>Messages</h1><p>${employer?'Candidate conversations linked to applications and hiring stages.':'Keep employer conversations organized by job and application.'}</p></div></div><div class="card chat-layout"><div class="chat-side"><div class="chat-search"><input placeholder="Search conversations"></div>${(employer?[['Ayesha Karim','Marketing Executive'],['Nusrat Jahan','Accounts Officer'],['Maliha Noor','UI/UX Designer']]:[['BluePeak Consumer','Digital Marketing Executive'],['Meridian Group','Accounts Officer'],['Northstar Studio','UI/UX Designer']]).map((x,i)=>`<div class="chat-item ${i===0?'active':''}"><div class="candidate-avatar">${initials(x[0])}</div><div><b>${x[0]}</b><small>${x[1]}</small></div>${i===0?'<span class="unread">2</span>':''}</div>`).join('')}</div><div class="chat-main"><div class="chat-head"><div><b>${employer?'Ayesha Karim':'BluePeak Consumer'}</b><div style="font-size:11px;color:var(--muted)">${employer?'Digital Marketing Executive · Interview stage':'Digital Marketing Executive · Interview scheduled'}</div></div><button class="btn btn-ghost">Application details</button></div><div class="messages"><div class="bubble them">${employer?'Thank you. Tomorrow after 3 PM works for me.':'We reviewed your application and would like to invite you to an interview.'}</div><div class="bubble me">${employer?'Perfect. I’ll send the interview details shortly.':'Thank you. Tomorrow after 3 PM works for me.'}</div></div><div class="chat-compose"><input placeholder="Write a message..."><button class="btn btn-primary" onclick="toast('Message sent')">Send</button></div></div></div>`}

function profile(){return shell(`<div class="page-head"><div><h1>Professional profile</h1><p>Your public career identity and source data for matching.</p></div><button class="btn btn-primary" onclick="toast('Profile saved')">Save changes</button></div><div class="profile-layout"><div><div class="card profile-card"><div class="profile-cover"><button class="cover-edit">Edit cover</button><div class="profile-avatar">TR</div></div><div class="profile-main"><div class="profile-head-actions"><div><h2>Tanvir Rahman</h2><p>Open to opportunities · ${state.sector}</p><p>Dhaka, Bangladesh · Open to remote</p></div><button class="btn btn-ghost">Preview public profile</button></div><div class="skills"><span class="skill">Communication</span><span class="skill">Problem solving</span><span class="skill">Digital tools</span><span class="skill">Teamwork</span></div></div></div>
  ${profileSection('About','Write a concise professional summary that works across your target roles.',`<textarea class="input" style="min-height:115px">Early-career professional building practical experience across digital products, operations and AI-assisted workflows. Interested in roles where technology, problem-solving and execution intersect.</textarea>`)}
  ${profileSection('Experience','Add paid work, internships, projects or relevant volunteer experience.',experienceEditor())}
  ${profileSection('Education','Degrees, diplomas and relevant study.',`<div class="timeline-item"><b>BSc in Computer Science & Engineering</b><span>University · 2023–Present</span><p>Relevant coursework and academic projects can be added here.</p></div><button class="btn btn-ghost">+ Add education</button>`)}
  ${profileSection('Skills','Add skills relevant to your target sectors. Avoid rating bars that imply unsupported precision.',`<div class="skill-editor"><span>Communication ×</span><span>Python ×</span><span>Excel ×</span><span>Research ×</span><span>Presentation ×</span><span>Problem Solving ×</span><input placeholder="Add a skill"></div>`)}
  ${profileSection('Certifications & licenses','Useful for regulated or credential-heavy roles.',`<div class="empty-inline"><span>＋</span><div><b>Add certification or professional license</b><small>Examples: nursing registration, accounting certification, teaching credential, platform certificates.</small></div></div>`)}
  ${profileSection('Portfolio & links','Show work samples, LinkedIn, personal website or portfolio.',`<div class="grid-12"><div class="col-6 field"><label>LinkedIn</label><input class="input" placeholder="https://linkedin.com/in/..."></div><div class="col-6 field"><label>Portfolio / website</label><input class="input" placeholder="https://..."></div></div>`)}
  </div><aside><div class="card panel sticky-panel"><h3>Profile strength</h3><div class="resume-score"><strong>82%</strong></div><div class="suggestion">Add one verified education record and a role-relevant work sample to strengthen employer trust.</div><h3>Job preferences</h3><div class="info-list"><div class="info-item"><span>Main sector</span><b>${state.sector}</b></div><div class="info-item"><span>Location</span><b>Dhaka / Remote</b></div><div class="info-item"><span>Job type</span><b>Full-time</b></div><div class="info-item"><span>Visibility</span><b>Recruiters</b></div></div><button class="btn btn-soft" style="width:100%">Edit preferences</button></div></aside></div>`)}
function profileSection(title,desc,body){return `<div class="card profile-section"><div class="section-row"><div><h3>${title}</h3><p>${desc}</p></div><button class="btn btn-ghost">Edit</button></div>${body}</div>`}
function experienceEditor(){return `<div class="timeline-item"><b>Junior Developer · Royal Bengal AI</b><span>Oct 2025–Present · Dhaka / Hybrid</span><p>Worked on practical product features, integrations and production workflows.</p></div><div class="timeline-item"><b>Project & academic work</b><span>Selected projects</span><p>Built web, AI and automation prototypes across several domains.</p></div><button class="btn btn-ghost">+ Add experience</button>`}

function notifications(){return shell(`<div class="page-head"><div><h1>Notifications</h1><p>Job alerts, application updates, recruiter activity and account notices.</p></div><button class="btn btn-ghost" onclick="toast('Marked all as read')">Mark all read</button></div><div class="card panel notification-list">${[['✦','6 new jobs match your profile','CareerMate AI · 12 min ago','mint'],['✓','Interview invitation received','BluePeak Consumer · 1h ago','blue'],['◫','Application moved to screening','Meridian Group · 3h ago','blue'],['♡','Saved job closes in 2 days','Northstar Studio · Today','warn'],['⚙','Complete your profile verification','Account · Yesterday','dark']].map(x=>`<div class="notification-item"><div class="notification-icon ${x[3]}">${x[0]}</div><div><b>${x[1]}</b><small>${x[2]}</small></div><span class="notif-unread"></span></div>`).join('')}</div>`)}

function settings(){return shell(`<div class="page-head"><div><h1>Settings & privacy</h1><p>Control account security, notifications, data and AI context.</p></div></div><div class="settings-layout"><div class="card panel settings-nav"><button class="active">Account</button><button>Privacy</button><button>Notifications</button><button>AI & data</button><button>Security</button><button>Accessibility</button></div><div class="card panel"><h3>Account</h3><div class="grid-12"><div class="col-6 field"><label>Full name</label><input class="input" value="Tanvir Rahman"></div><div class="col-6 field"><label>Email</label><input class="input" value="tanvir@example.com"></div></div><h3 style="margin-top:26px">AI controls</h3>${[['Use profile for job recommendations',true],['Use saved jobs as preference signals',true],['Use application history for AI coaching',false],['Allow profile in recruiter search',true]].map(x=>`<div class="setting-row"><div><b>${x[0]}</b><small>You can change this at any time.</small></div><div class="switch ${x[1]?'on':''}" onclick="this.classList.toggle('on')"></div></div>`).join('')}<h3 style="margin-top:26px">Account security</h3><div class="setting-row"><div><b>Two-factor authentication</b><small>Add an extra layer of security.</small></div><button class="btn btn-ghost">Enable</button></div><button class="btn btn-primary" onclick="toast('Settings saved')">Save settings</button></div></div>`)}

function companySetup(){return `<div class="onboarding-shell"><div class="onboarding-card"><div style="display:flex;justify-content:center">${brand()}</div><div class="card onboard-panel" style="margin-top:38px"><span class="badge mint">Employer setup</span><h1>Set up your company profile</h1><p class="section-copy">Verified company information improves candidate trust and job quality.</p><div class="grid-12"><div class="col-6 field"><label>Company name</label><input class="input" placeholder="Company name"></div><div class="col-6 field"><label>Industry</label><select class="input">${categories.filter(x=>!['All','Other'].includes(x[0])).map(x=>`<option>${x[0]}</option>`).join('')}<option>Other</option></select></div><div class="col-6 field"><label>Company size</label><select class="input"><option>1–10</option><option>11–50</option><option>51–200</option><option>201–500</option><option>500+</option></select></div><div class="col-6 field"><label>Location</label><input class="input" placeholder="Dhaka, Bangladesh"></div><div class="col-12 field"><label>Website</label><input class="input" placeholder="https://company.com"></div></div><div class="onboard-actions"><button class="btn btn-ghost" onclick="go('/signup')">Back</button><button class="btn btn-primary" onclick="go('/employer')">Create employer workspace</button></div></div></div></div>`}

function employerDashboard(){return shell(`<div class="page-head"><div><h1>Employer overview</h1><p>Hiring performance across all active job families.</p></div><button class="btn btn-primary" onclick="go('/post-job')">+ Post a job</button></div><div class="application-stats"><div class="card metric"><small>Active jobs</small><strong>8</strong><div class="trend">4 sectors</div></div><div class="card metric"><small>New applicants</small><strong>42</strong><div class="trend">Today</div></div><div class="card metric"><small>Interviews</small><strong>11</strong><div class="trend">This week</div></div><div class="card metric"><small>Open offers</small><strong>3</strong></div></div><div class="grid-12"><div class="col-8 card panel"><div class="section-row"><div><h3>Hiring pipeline</h3><p>All active roles</p></div><button class="btn btn-ghost" onclick="go('/pipeline')">Open pipeline</button></div><div class="pipeline-mini">${[['Applied',126],['Screening',54],['Shortlisted',28],['Interview',11],['Offer',3]].map(x=>`<div><span>${x[1]}</span><small>${x[0]}</small></div>`).join('')}</div><h3 style="margin-top:26px">Recent applicants</h3>${candidates.slice(0,4).map(candidateRow).join('')}</div><div class="col-4"><div class="card panel ai-employer-card"><span class="badge mint">✦ Hiring AI</span><h3>8 candidates need review</h3><p>AI found strong evidence for the required criteria, but final screening decisions remain with your hiring team.</p><button class="btn btn-primary" style="width:100%" onclick="go('/candidates')">Review candidates</button></div><div class="card panel" style="margin-top:16px"><h3>Job performance</h3><div class="info-list"><div class="info-item"><span>Marketing Executive</span><b>54 applicants</b></div><div class="info-item"><span>Accounts Officer</span><b>71 applicants</b></div><div class="info-item"><span>UI/UX Designer</span><b>93 applicants</b></div></div></div></div></div>`,true)}

function postJob(){return shell(`<div class="page-head"><div><h1>Post a job</h1><p>Use a role-specific structure instead of one generic engineering template.</p></div><button class="btn btn-ghost" onclick="toast('Draft saved')">Save draft</button></div><div class="grid-12"><div class="col-8"><div class="card form-section"><h3>1. Job basics</h3><div class="grid-12"><div class="col-7 field"><label>Job title</label><input class="input" placeholder="e.g. Accounts Officer"></div><div class="col-5 field"><label>Sector / function</label><select class="input" id="jobSector" onchange="updateRequirementHint()">${categories.filter(x=>x[0]!=='All').map(x=>`<option>${x[0]}</option>`).join('')}</select></div><div class="col-4 field"><label>Job type</label><select class="input"><option>Full-time</option><option>Part-time</option><option>Internship</option><option>Contract</option></select></div><div class="col-4 field"><label>Work mode</label><select class="input"><option>On-site</option><option>Hybrid</option><option>Remote</option></select></div><div class="col-4 field"><label>Experience level</label><select class="input"><option>Entry level</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select></div><div class="col-6 field"><label>Location</label><input class="input" placeholder="Dhaka, Bangladesh"></div><div class="col-3 field"><label>Salary min</label><input class="input" placeholder="৳ 35,000"></div><div class="col-3 field"><label>Salary max</label><input class="input" placeholder="৳ 50,000"></div></div></div>
  <div class="card form-section"><div class="section-row"><div><h3>2. Description</h3><p>Be specific about actual responsibilities.</p></div><button class="btn btn-soft" onclick="toast('AI improved clarity without adding new requirements')">✦ Improve with AI</button></div><textarea class="input rich-textarea" placeholder="Describe the role, team and business context..."></textarea></div>
  <div class="card form-section"><h3>3. Responsibilities & requirements</h3><div id="requirementHint" class="suggestion"><b>Technology example:</b> use concrete tools, systems and engineering responsibilities.</div><div class="field"><label>Key responsibilities</label><textarea class="input rich-textarea" placeholder="One responsibility per line..."></textarea></div><div class="grid-12"><div class="col-6 field"><label>Must-have requirements</label><textarea class="input" style="min-height:130px" placeholder="Required education, experience, skills or license..."></textarea></div><div class="col-6 field"><label>Preferred requirements</label><textarea class="input" style="min-height:130px" placeholder="Nice-to-have criteria..."></textarea></div></div></div>
  <div class="card form-section"><h3>4. Application & screening</h3><div class="setting-row"><div><b>Accept applications inside CareerMate</b><small>Candidates submit CV, profile and screening answers.</small></div><div class="switch on"></div></div><div class="field"><label>Screening question</label><input class="input" value="How many years of relevant experience do you have?"></div><button class="btn btn-ghost">+ Add screening question</button></div></div>
  <div class="col-4"><div class="card panel sticky-panel"><span class="badge mint">✦ Job quality assistant</span><h3>Before publishing</h3><div class="quality-list"><div><span>✓</span> Clear title</div><div><span>✓</span> Salary range</div><div><span>○</span> Add 3 responsibilities</div><div><span>○</span> Separate must-have vs preferred</div></div><button class="btn btn-primary" style="width:100%;margin-top:14px" onclick="toast('Job published')">Publish job</button><button class="btn btn-ghost" style="width:100%;margin-top:8px">Preview as candidate</button></div></div></div>`,true)}
function updateRequirementHint(){const s=document.getElementById('jobSector')?.value;const hints={Finance:'Include accounting scope, ERP/Excel expectations, tax/VAT knowledge and any required certification.',Healthcare:'Include required professional registration/license, clinical area, shift pattern and patient-safety responsibilities.',Education:'Include subject/grade, curriculum, teaching load, classroom expectations and required credentials.',Sales:'Include sales motion, target/commission structure, CRM and territory/account scope.',Design:'Include portfolio expectations, tools, research/prototyping scope and design-system responsibilities.',Marketing:'Include channels, campaign responsibilities, reporting metrics and budget scope.'};document.getElementById('requirementHint').innerHTML=`<b>${s} guidance:</b> ${hints[s]||'Use concrete role-specific responsibilities, measurable scope and only genuinely required criteria.'}`}

function manageJobs(){return shell(`<div class="page-head"><div><h1>Manage jobs</h1><p>Active, paused, draft and closed roles across sectors.</p></div><button class="btn btn-primary" onclick="go('/post-job')">+ Post job</button></div><div class="filter-toolbar"><button class="filter active">All 12</button><button class="filter">Active 8</button><button class="filter">Draft 2</button><button class="filter">Paused 1</button><button class="filter">Closed 1</button></div><div class="card panel table-wrap"><table class="table"><thead><tr><th>Role</th><th>Sector</th><th>Status</th><th>Applicants</th><th>Shortlisted</th><th>Posted</th><th></th></tr></thead><tbody>${jobs.slice(0,8).map((j,i)=>`<tr><td><b>${j.title}</b><small>${j.company}</small></td><td>${j.category}</td><td><span class="status ${i===6?'applied':'offer'}">${i===6?'Paused':'Active'}</span></td><td>${j.applicants}</td><td>${Math.max(3,Math.round(j.applicants*.18))}</td><td>${j.posted}</td><td><button class="btn btn-ghost">Manage</button></td></tr>`).join('')}</tbody></table></div>`,true)}
function candidateRow(c){return `<div class="candidate-card" onclick="go('/candidate/${c.id}')"><div class="candidate-avatar">${initials(c.name)}</div><div><b>${c.name}</b><small>${c.role} · ${c.exp} · ${c.sector}</small><div class="skills">${c.skills.map(s=>`<span class="skill">${s}</span>`).join('')}</div></div><div class="candidate-score"><span class="badge mint">${c.score}% match</span><small>${c.stage}</small></div></div>`}
function candidatesPage(){return shell(`<div class="page-head"><div><h1>Candidates</h1><p>Review evidence by role instead of using one generic technical score.</p></div><button class="btn btn-soft">Export shortlist</button></div><div class="candidate-toolbar card"><div class="search-field"><span>⌕</span><input placeholder="Search candidates"></div><select class="input"><option>All jobs</option>${jobs.slice(0,6).map(j=>`<option>${j.title}</option>`).join('')}</select><select class="input"><option>All stages</option><option>Applied</option><option>Screening</option><option>Shortlisted</option><option>Interview</option></select></div><div class="grid-12"><div class="col-8 card panel">${candidates.map(candidateRow).join('')}</div><div class="col-4 card panel sticky-panel"><span class="badge mint">✦ AI Screening Summary</span><h3>Explainable, not automatic rejection</h3><div class="suggestion">5 candidates meet all must-have requirements for their respective roles.</div><div class="suggestion">2 profiles are missing evidence for a preferred criterion.</div><div class="suggestion">1 regulated-role profile needs manual license verification.</div><button class="btn btn-primary" style="width:100%">Review evidence</button></div></div>`,true)}
function candidateDetail(id){const c=candidates.find(x=>x.id==id)||candidates[0];return shell(`<div class="back-row"><button class="btn btn-ghost" onclick="go('/candidates')">← Candidates</button></div><div class="grid-12"><div class="col-8"><div class="card candidate-profile-head"><div class="candidate-avatar xl">${initials(c.name)}</div><div><span class="badge dark">${c.sector}</span><h1>${c.name}</h1><p>${c.role} · ${c.exp} · Dhaka, Bangladesh</p><div class="skills">${c.skills.map(s=>`<span class="skill">${s}</span>`).join('')}</div></div><div class="candidate-profile-actions"><button class="btn btn-primary" onclick="toast('Candidate shortlisted')">Shortlist</button><button class="btn btn-ghost">Message</button></div></div><div class="card detail-section"><h3>Application</h3><p>Candidate profile, CV, screening responses and any portfolio links would appear here.</p><h3>Experience evidence</h3><div class="timeline-item"><b>${c.role}</b><span>${c.exp} relevant experience</span><p>Role-specific responsibilities and evidence parsed from the submitted CV.</p></div><h3>Education & credentials</h3><p>Education and professional-license data should be displayed here with verification status where applicable.</p></div></div><div class="col-4"><div class="card panel sticky-panel"><span class="badge mint">${c.score}% match</span><h3>Requirement evidence</h3><div class="match-breakdown">${[['Must-have skills',94],['Experience',88],['Education',84],['Location',100]].map(x=>`<div class="match-row"><span>${x[0]}</span><div class="progress"><span style="width:${x[1]}%"></span></div><b>${x[1]}%</b></div>`).join('')}</div><div class="suggestion"><b>Human review needed:</b> AI summarizes submitted evidence; it should not make the final hiring decision.</div><button class="btn btn-primary" style="width:100%">Move to interview</button></div></div></div>`,true)}

function pipeline(){const cols=[['Applied',candidates.slice(2)],['Screening',candidates.slice(1,4)],['Shortlisted',candidates.slice(0,2)],['Interview',candidates.slice(3)],['Offer',[candidates[2]]]];return shell(`<div class="page-head"><div><h1>Hiring pipeline</h1><p>Move candidates through configured stages.</p></div><button class="btn btn-soft">Configure stages</button></div><div class="pipeline wide">${cols.map(col=>`<div class="pipe-col"><div class="pipe-head"><span>${col[0]}</span><span>${col[1].length}</span></div>${col[1].map(c=>`<div class="pipe-card" onclick="go('/candidate/${c.id}')"><b>${c.name}</b><p>${c.role}</p><div><span class="badge mint">${c.score}%</span></div></div>`).join('')}</div>`).join('')}</div>`,true)}
function analytics(){return shell(`<div class="page-head"><div><h1>Hiring analytics</h1><p>Funnel quality, source performance and time-to-hire by sector.</p></div><button class="btn btn-soft">Last 30 days ⌄</button></div><div class="application-stats"><div class="card metric"><small>Applications</small><strong>382</strong><div class="trend">+18%</div></div><div class="card metric"><small>Qualified</small><strong>146</strong><div class="trend">38.2%</div></div><div class="card metric"><small>Interview rate</small><strong>16.4%</strong></div><div class="card metric"><small>Median time to shortlist</small><strong>2.8d</strong></div></div><div class="grid-12"><div class="col-8 card panel"><h3>Applications by week</h3><div class="chart">${[42,65,55,82,76,96].map(h=>`<div class="bar" style="height:${h}%"></div>`).join('')}</div></div><div class="col-4 card panel"><h3>Applications by sector</h3>${[['Technology',31],['Marketing',24],['Finance',18],['Operations',15],['Other',12]].map(x=>`<div class="sector-bar"><div><span>${x[0]}</span><b>${x[1]}%</b></div><div class="progress"><span style="width:${x[1]*2.7}%"></span></div></div>`).join('')}</div><div class="col-6 card panel"><h3>Source quality</h3><div class="info-list"><div class="info-item"><span>CareerMate recommendations</span><b>84%</b></div><div class="info-item"><span>Direct search</span><b>71%</b></div><div class="info-item"><span>Referral</span><b>89%</b></div><div class="info-item"><span>External link</span><b>63%</b></div></div></div><div class="col-6 card panel"><h3>Hiring health</h3><div class="suggestion">Finance roles have a high screening-to-interview drop. Review whether requirements are unnecessarily broad.</div><div class="suggestion">Design roles receive many applications but portfolio review is taking 4.1 days.</div></div></div>`,true)}
function companyProfile(){return shell(`<div class="page-head"><div><h1>Company profile</h1><p>Employer brand, verification and candidate-facing information.</p></div><button class="btn btn-primary" onclick="toast('Company profile saved')">Save changes</button></div><div class="grid-12"><div class="col-8 card panel"><div class="field"><label>Company name</label><input class="input" value="Nexa Labs"></div><div class="field"><label>About company</label><textarea class="input" style="min-height:140px">We build practical products and services for customers across South Asia.</textarea></div><div class="grid-12"><div class="col-6 field"><label>Primary industry</label><select class="input"><option>Technology</option><option>Financial Services</option><option>Healthcare</option><option>Education</option><option>Retail</option><option>Manufacturing</option><option>Other</option></select></div><div class="col-6 field"><label>Company size</label><select class="input"><option>51–200</option></select></div><div class="col-6 field"><label>Headquarters</label><input class="input" value="Dhaka, Bangladesh"></div><div class="col-6 field"><label>Website</label><input class="input" value="https://nexalabs.example"></div></div><h3>Workplace & benefits</h3><div class="skill-editor"><span>Hybrid work ×</span><span>Learning budget ×</span><span>Health benefits ×</span><input placeholder="Add benefit"></div></div><div class="col-4 card panel"><div class="profile-cover" style="height:120px;border-radius:14px"><div class="profile-avatar" style="width:80px;height:80px;bottom:-40px">NL</div></div><div style="padding:52px 10px 10px"><h3>Nexa Labs</h3><p class="muted-copy">Technology · Dhaka</p><span class="badge mint">✓ Verified employer</span><div class="info-list" style="margin-top:16px"><div class="info-item"><span>Jobs</span><b>8 active</b></div><div class="info-item"><span>Followers</span><b>4.2k</b></div></div></div></div></div>`,true)}

function adminDashboard(){return shell(`<div class="page-head"><div><h1>Platform admin</h1><p>Moderation, trust & safety, users, employers and platform health.</p></div><span class="badge warn">Admin access</span></div><div class="application-stats"><div class="card metric"><small>Active users</small><strong>18.4k</strong></div><div class="card metric"><small>Active jobs</small><strong>1,284</strong></div><div class="card metric"><small>Verified employers</small><strong>612</strong></div><div class="card metric"><small>Open reports</small><strong>23</strong></div></div><div class="grid-12"><div class="col-7 card panel"><h3>Moderation queue</h3>${[['Job: Finance Executive','Potential fee/scam wording','High'],['Employer: ABC Services','Verification documents pending','Medium'],['Job: Remote Data Entry','Duplicate / suspicious listing','High'],['User report','Harassment in employer message','High']].map(x=>`<div class="moderation-row"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="badge ${x[2]==='High'?'warn':'dark'}">${x[2]}</span><button class="btn btn-ghost">Review</button></div>`).join('')}</div><div class="col-5 card panel"><h3>Trust & safety signals</h3><div class="info-list"><div class="info-item"><span>Jobs auto-flagged today</span><b>17</b></div><div class="info-item"><span>Employer verifications pending</span><b>31</b></div><div class="info-item"><span>User appeals</span><b>8</b></div><div class="info-item"><span>Resolved reports (7d)</span><b>126</b></div></div></div></div>`,false,true)}
function adminUsers(){return shell(`<div class="page-head"><div><h1>User management</h1><p>Candidates, employer accounts and access status.</p></div></div><div class="card panel table-wrap"><table class="table"><thead><tr><th>User</th><th>Type</th><th>Status</th><th>Joined</th><th>Verification</th><th></th></tr></thead><tbody>${[['Tanvir Rahman','Candidate','Active','Sep 10','Email'],['Nexa Labs','Employer','Active','Sep 07','Verified'],['BluePeak Consumer','Employer','Active','Sep 02','Verified'],['Example User','Candidate','Restricted','Aug 28','Pending']].map(x=>`<tr><td><b>${x[0]}</b></td><td>${x[1]}</td><td><span class="status ${x[2]==='Active'?'offer':'reject'}">${x[2]}</span></td><td>${x[3]}</td><td>${x[4]}</td><td><button class="btn btn-ghost">View</button></td></tr>`).join('')}</tbody></table></div>`,false,true)}
function adminJobs(){return shell(`<div class="page-head"><div><h1>Job moderation</h1><p>Review listings, employer trust signals and reports.</p></div></div><div class="job-list">${jobs.slice(0,6).map(j=>`<div class="card moderation-job"><div class="job-logo">${j.logo}</div><div><b>${j.title}</b><small>${j.company} · ${j.category} · ${j.posted}</small></div><span class="badge mint">Published</span><button class="btn btn-ghost">Review</button></div>`).join('')}</div>`,false,true)}
function adminReports(){return shell(`<div class="page-head"><div><h1>Reports & safety</h1><p>Candidate and employer reports that require platform review.</p></div></div><div class="card panel">${[['Payment requested outside platform','Job listing','Open','High'],['Misleading salary range','Job listing','Investigating','Medium'],['Inappropriate recruiter message','Conversation','Open','High'],['Fake credential concern','Candidate profile','Needs evidence','Medium']].map(x=>`<div class="report-row"><div><b>${x[0]}</b><small>${x[1]}</small></div><span class="status applied">${x[2]}</span><span class="badge ${x[3]==='High'?'warn':'dark'}">${x[3]}</span><button class="btn btn-ghost">Open case</button></div>`).join('')}</div>`,false,true)}

function publicJobs(){return `<div class="public-nav"><div class="container nav-inner">${brand()}<div class="nav-actions"><button class="btn btn-ghost" onclick="go('/login')">Sign in</button><button class="btn btn-primary" onclick="go('/signup')">Create account</button></div></div></div><div class="container section" style="padding-top:50px"><div class="page-head"><div><h1 style="font:800 38px Manrope">Explore jobs</h1><p>Browse multi-sector opportunities. Sign in for AI ranking and applications.</p></div></div><div class="category-scroll">${categories.map(c=>`<button class="category-pill">${c[1]} ${c[0]}</button>`).join('')}</div><div class="grid-12"><div class="col-8"><div class="job-list">${jobs.map(jobCard).join('')}</div></div><div class="col-4 card panel sticky-panel"><h3>Ready to apply?</h3><p class="muted-copy">Create a candidate profile, upload your CV and CareerMate can rank jobs based on your actual background.</p><button class="btn btn-primary" style="width:100%" onclick="go('/signup')">Create free profile</button></div></div></div>`}
function notFound(){return `<div class="not-found">${brand()}<h1>404</h1><p>This prototype route doesn’t exist.</p><button class="btn btn-primary" onclick="go('/')">Back home</button></div>`}

function render(){
  const r=route(); let html='';
  if(r==='/') html=landing();
  else if(r==='/login') html=auth('login');
  else if(r==='/signup') html=auth('signup');
  else if(r==='/onboarding') html=onboarding();
  else if(r==='/company-setup') html=companySetup();
  else if(r==='/dashboard') html=dashboard();
  else if(r==='/jobs') html=jobsPage();
  else if(r==='/jobs-public') html=publicJobs();
  else if(r.startsWith('/job/')) html=jobDetail(r.split('/').pop());
  else if(r.startsWith('/apply/')) html=applyPage(r.split('/').pop());
  else if(r.startsWith('/application-success/')) html=applicationSuccess(r.split('/').pop());
  else if(r==='/saved') html=savedJobs();
  else if(r==='/resume') html=resumePage();
  else if(r==='/tracker') html=tracker();
  else if(r==='/ai-coach') html=aiCoach();
  else if(r==='/messages') html=messages();
  else if(r==='/profile') html=profile();
  else if(r==='/notifications') html=notifications();
  else if(r==='/settings') html=settings();
  else if(r==='/employer') html=employerDashboard();
  else if(r==='/post-job') html=postJob();
  else if(r==='/manage-jobs') html=manageJobs();
  else if(r==='/candidates') html=candidatesPage();
  else if(r.startsWith('/candidate/')) html=candidateDetail(r.split('/').pop());
  else if(r==='/pipeline') html=pipeline();
  else if(r==='/analytics') html=analytics();
  else if(r==='/company-profile') html=companyProfile();
  else if(r==='/employer-messages') html=employerMessages();
  else if(r==='/admin') html=adminDashboard();
  else if(r==='/admin-users') html=adminUsers();
  else if(r==='/admin-jobs') html=adminJobs();
  else if(r==='/admin-reports') html=adminReports();
  else html=notFound();
  app.innerHTML=html;window.scrollTo(0,0);
}
window.addEventListener('hashchange',render);render();
